channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal==8.4.11
  - picard==3.1.1
  - gatk4==4.5.0.0
  - biopython==1.83
  - ruamel.yaml==0.18.6
  - kraken==1.1.1
  - bwa==0.7.18
  - git
  - pip
  - pip:
      # - serum-readfilter==1.0  # Installed by custom_install.sh
      - bifrostlib
