#-Basic info----------------------------------------------------------------------------------------
display_name: sp_cdiff
name: sp_cdiff__v0.0.1
version:
  schema: ["v0_0_1"]
  code: v0.0.1
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    Cdiff related analysis.
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [toxin_profile]
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  db: "cdiff_fbi/db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      mlst:
        summary:
          sequence_type:
      species_detection:
        summary:
          species: Clostridioides difficile
  components:
    analyzer:
      status:
#---------------------------------------------------------------------------------------------------
